services:
  bot:
    build: .
    env_file: .env
    volumes:
    - ./bot.py:/app/bot.py
    - ./users.yml:/app/users.yml
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: python /app/bot.py